### ISSUE TITLE
Is Spyder-vim still under development?

### ISSUE THREAD

**Issue by Ubaldo79** [spyder-ide/spyder-vim#76]
… just wondering 😊

**Comment by CAM-Gerlach** [comment]
Unfortunately, its mostly inactive right now due to lack of developer bandwidth; the primary blocker is #75 . Due to recent changes in the Spyder team and funding, it seems unlikely this will change too much in the immediate future at least with respect to the core team, but if someone was willing to step up to help, it certainly could...

**Comment by Ubaldo79** [comment]
I wish I could! :( 
I make small donations every once in a while but I don’t think I could support in coding. :( 
It seems that Spyder is entirely written in Python and I am a very newbie. 
Certainly, Spyder + vim would be killer though. Hopefully more skilled developers will start to support you guys!
